language: php
php:
- 5.5
install:
- composer install --no-interaction --prefer-source
script:
- if [[ ${TRAVIS_SECURE_ENV_VARS} == "false" ]]; then ./vendor/bin/phing build -verbose
- if [[ ${TRAVIS_SECURE_ENV_VARS} == "true" ]]; then ./vendor/bin/phing build-full -verbose
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
deploy:
  provider: heroku
  app: hrphp-org
  api_key:
    secure: QAWBdIWLp3M8+q0Xwe/ScRG9enmH7b7mXjJeVKhglQmtcSSyBHRdtw2ZfYKJCdIYWfQFCdq8NXtZugJ7pT2hSTQQkwk6sSyLcOjmryN6lReJepcrJSO50nxBVhTMVm6SGRRqxhsTobnCruZh7YOXvzhu/eIcynFR3L6zP3QL8qE=
env:
  global:
  - secure: x2Vix7ZaKMV0a2U8i+pWaNwbzqzH5DORb0IYWplhQcnf5CgHnXigq8dp/1IeHFOn7ARZsf6950BcbVBJQuEDrHzyLtl5Sn49AGVSMmIzIt/+plB5PYFi/AwDD9SXA7EVlfl7YMZOA1ATBPthoB1mK72UvvEn02UdyUvjxOHxKpI=
  - secure: tRl+uEEMOBPrkvDrj79zLoY3FIP1fhavepPHov2am5iwM5tXGXUbNkTc/38jJDgO48fXgIIAMFvc3GgE8J7Aw4FzcfkGu4LWnGCGLqvIGl1zXmgBDGg1caZWB2Poe3cc5E4oyBdtFP+Nv6Hig+S8/icfFTzwqXc32yqzK096fXM=
  - secure: mcytV4Gbt7Z0afmsKabfumdb2Ud+oz2yCqp0FXuupzpbyeXowY2ba3MYaq2uC8kR6WGG58HzViQ4bsKX6h60xKeFRpv1iA61+T+7KYyUIah1b4M11o8IJC4wV+0MkBDGif+xPCMX4b2IYXkYo8QTzGHMFsB15HTYq1wovAv2Dio=
  - secure: Xh7uNTfj1Pk0lIMr198kakClOYZeiqpTkRxkq4g71fsKriV2P1u87q7RGfOmlmk5DZTN0FwwLh1TzL1Q4Y7OsWPpjjNyvPFRz78eM4Hx2BvkEeIT2Jl7IyFcTAuMq2xzyw+s5C4sCPYUtrBo5Y+79U/zCWxqtyvG6VbMaMahdEI=
  - secure: 2tD9x1V6fMPAjhG++8g1gHtIK5cHr8wd8c+WLUYfSs1SNmQ6oPpQ6eEaiPyH2CNiYW83WJcf6TlUwfZe12jpmXGOLL3jCqKfJHeZxU7Cv1rINJ8KgLcEUEzWuxxmezWCczK+thQ59nL5bnbnoItoGbgd7v/PrxTe5/di1eTCQ38=
